//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.10 at 11:23:28 PM CST 
//


package me.demo.qa.startup.entity.xsd.geocoding;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the me.demo.qa.startup.entity.xsd.geocoding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _Direction_QNAME = new QName("", "direction");
    private final static QName _Street_QNAME = new QName("", "street");
    private final static QName _CityCode_QNAME = new QName("", "cityCode");
    private final static QName _Addr_QNAME = new QName("", "addr");
    private final static QName _Lng_QNAME = new QName("", "lng");
    private final static QName _Business_QNAME = new QName("", "business");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _PoiType_QNAME = new QName("", "poiType");
    private final static QName _Distance_QNAME = new QName("", "distance");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _FormattedAddress_QNAME = new QName("", "formatted_address");
    private final static QName _Province_QNAME = new QName("", "province");
    private final static QName _SematicDescription_QNAME = new QName("", "sematic_description");
    private final static QName _District_QNAME = new QName("", "district");
    private final static QName _Y_QNAME = new QName("", "y");
    private final static QName _Lat_QNAME = new QName("", "lat");
    private final static QName _X_QNAME = new QName("", "x");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: me.demo.qa.startup.entity.xsd.geocoding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AddressComponent }
     * 
     */
    public AddressComponent createAddressComponent() {
        return new AddressComponent();
    }

    /**
     * Create an instance of {@link StreetNumber }
     * 
     */
    public StreetNumber createStreetNumber() {
        return new StreetNumber();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link Pois }
     * 
     */
    public Pois createPois() {
        return new Pois();
    }

    /**
     * Create an instance of {@link Poi }
     * 
     */
    public Poi createPoi() {
        return new Poi();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link Tel }
     * 
     */
    public Tel createTel() {
        return new Tel();
    }

    /**
     * Create an instance of {@link Zip }
     * 
     */
    public Zip createZip() {
        return new Zip();
    }

    /**
     * Create an instance of {@link PoiRegions }
     * 
     */
    public PoiRegions createPoiRegions() {
        return new PoiRegions();
    }

    /**
     * Create an instance of {@link GeocoderSearchResponse }
     * 
     */
    public GeocoderSearchResponse createGeocoderSearchResponse() {
        return new GeocoderSearchResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<BigInteger> createStatus(BigInteger value) {
        return new JAXBElement<BigInteger>(_Status_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "direction")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDirection(String value) {
        return new JAXBElement<String>(_Direction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "street")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cityCode")
    public JAXBElement<BigInteger> createCityCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_CityCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addr")
    public JAXBElement<String> createAddr(String value) {
        return new JAXBElement<String>(_Addr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lng")
    public JAXBElement<BigDecimal> createLng(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Lng_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "business")
    public JAXBElement<String> createBusiness(String value) {
        return new JAXBElement<String>(_Business_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "poiType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPoiType(String value) {
        return new JAXBElement<String>(_PoiType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distance")
    public JAXBElement<BigInteger> createDistance(BigInteger value) {
        return new JAXBElement<BigInteger>(_Distance_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "formatted_address")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFormattedAddress(String value) {
        return new JAXBElement<String>(_FormattedAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<String>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sematic_description")
    public JAXBElement<String> createSematicDescription(String value) {
        return new JAXBElement<String>(_SematicDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "district")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDistrict(String value) {
        return new JAXBElement<String>(_District_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y")
    public JAXBElement<BigDecimal> createY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Y_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lat")
    public JAXBElement<BigDecimal> createLat(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Lat_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x")
    public JAXBElement<BigDecimal> createX(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_X_QNAME, BigDecimal.class, null, value);
    }

}
