//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.10 at 11:23:28 PM CST 
//


package me.demo.qa.startup.entity.xsd.geocoding;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}addr"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}direction"/>
 *           &lt;element ref="{}distance"/>
 *           &lt;element ref="{}name"/>
 *           &lt;element ref="{}poiType"/>
 *           &lt;element ref="{}point"/>
 *           &lt;element ref="{}tel"/>
 *           &lt;element ref="{}zip"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addr",
    "directionOrDistanceOrName"
})
@XmlRootElement(name = "poi")
public class Poi {

    @XmlElement(required = true)
    protected String addr;
    @XmlElementRefs({
        @XmlElementRef(name = "zip", type = Zip.class, required = false),
        @XmlElementRef(name = "poiType", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "distance", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "direction", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tel", type = Tel.class, required = false),
        @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "point", type = Point.class, required = false)
    })
    protected List<Object> directionOrDistanceOrName;

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the directionOrDistanceOrName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the directionOrDistanceOrName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirectionOrDistanceOrName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Zip }
     * {@link Tel }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link Point }
     * 
     * 
     */
    public List<Object> getDirectionOrDistanceOrName() {
        if (directionOrDistanceOrName == null) {
            directionOrDistanceOrName = new ArrayList<Object>();
        }
        return this.directionOrDistanceOrName;
    }

}
