//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 04:22:54 PM CST 
//


package me.demo.qa.startup.entity.xsd.weather;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fl" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fx" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="h" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="js" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sd" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="wd" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "qw")
public class Qw {

    @XmlAttribute(name = "fl", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fl;
    @XmlAttribute(name = "fx", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fx;
    @XmlAttribute(name = "h", required = true)
    protected BigInteger h;
    @XmlAttribute(name = "js", required = true)
  protected BigDecimal js;
    @XmlAttribute(name = "sd", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sd;
    @XmlAttribute(name = "wd", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String wd;

    /**
     * Gets the value of the fl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFl() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFl(String value) {
        this.fl = value;
    }

    /**
     * Gets the value of the fx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFx() {
        return fx;
    }

    /**
     * Sets the value of the fx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFx(String value) {
        this.fx = value;
    }

    /**
     * Gets the value of the h property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setH(BigInteger value) {
        this.h = value;
    }

    /**
   * Gets the value of the js property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getJs() {
        return js;
    }

    /**
   * Sets the value of the js property.
   * 
   * @param value allowed object is {@link BigDecimal }
   * 
   */
  public void setJs(BigDecimal value) {
        this.js = value;
    }

    /**
     * Gets the value of the sd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSd() {
        return sd;
    }

    /**
     * Sets the value of the sd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSd(String value) {
        this.sd = value;
    }

    /**
     * Gets the value of the wd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWd() {
        return wd;
    }

    /**
     * Sets the value of the wd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWd(String value) {
        this.wd = value;
    }

}
